site_name: toolprotocol
site_description: Documentation for toolprotocol
repo_name: jonwraymond/toolprotocol
repo_url: https://github.com/jonwraymond/toolprotocol
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Home: index.md
  - Design Notes: design-notes.md
  - User Journey: user-journey.md
theme:
  name: material
